name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:    
      - name: mkdirs
        run: |
          mkdir _build
      - name: Slidy
        uses: docker://pandoc/latex
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            -t slidy
            --output=_build/index.html
            README.md
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
