name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: mkdirs
        run: |
          mkdir _build
          cp -r docs _build
      - name: Slidy
        uses: docker://pandoc/latex:latest
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            -t slidy
            --output=_build/index.html
            README.md
      - name: PDF
        uses: docker://pandoc/latex:latest
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=_build/README.pdf
            README.md
      - name: PDF paper
        uses: docker://pandoc/latex:latest
        with:
          args: >-  # allows you to break string into multiple lines
            --csl=docs/ieee-with-url.csl
            --citeproc
            --resource-path='docs'
            -s README.md
            -o paper.pdf
            --template docs/memo.latex
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
